# Define a 'Persistent Volume Claim' (PVC) for MariaDB Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Configure 'Deployment' of MariaDB server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: database
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
    spec:
      containers:
        - image: mariadb:latest
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: school
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
---
# Define a 'Service' to expose MariaDB to other services
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
    tier: database
  clusterIP: None
